package io.rekursio.rest.error.exception

internal object ErrorCode {

    const val UNKNOWN_ERROR = "UNKNOWN_ERROR"

}